[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mysqli",
  "php82Extensions.mbstring",
  "php82Extensions.zip",
  "php82Extensions.intl",
  "php82Extensions.opcache",
  "php82Extensions.bcmath",
  "php82Extensions.curl",
  "php82Extensions.xml",
  "php82Extensions.gd"
]
nixPkgs = [
  "php81",
  "php81Extensions.pdo_mysql",
  "php81Extensions.mysqli",
  "php81Extensions.mbstring",
  "php81Extensions.zip",
  "php81Extensions.intl",
  "php81Extensions.opcache",
  "php81Extensions.bcmath",
  "php81Extensions.curl",
  "php81Extensions.xml",
  "php81Extensions.gd"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache", 
    "php artisan view:cache"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
