[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mysqli",
  "php82Extensions.mbstring",
  "php82Extensions.zip",
  "php82Extensions.intl",
  "php82Extensions.opcache",
  "php82Extensions.bcmath"
]
